apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "quickwit.fullname" . }}-indexer
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "quickwit.fullname" . }}-headless
  selector:
    matchLabels:
      {{- include "quickwit.indexer.selectorLabels" . | nindent 6 }}
  updateStrategy:
    {{- toYaml .Values.indexer.updateStrategy | nindent 4 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "quickwit.indexer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "quickwit.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "quickwit.environment" . | nindent 12 }}
            {{- range $key, $value := .Values.indexer.extraEnv }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          args: ["run", "--service", "indexer"]
          ports:
            - name: http
              containerPort: 7280
              protocol: TCP
            - name: grpc
              containerPort: 7281
              protocol: TCP
            - name: discovery 
              containerPort: 7282
              protocol: UDP
          livenessProbe:
            {{- toYaml .Values.indexer.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.indexer.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /quickwit/node.yaml
              subPath: node.yaml
            - name: data
              mountPath: /quickwit/qwdata
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ template "quickwit.fullname" . }}
            items:
              - key: node.yaml
                path: node.yaml
        - name: data
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
